version: "3"

services:
  office-application:
    build:
      context: ./office
    container_name: office-application
    ports:
      - "80:80"
    environment:
      - RECIPES_SERVICE_URL=http://localhost:5005
      - INGREDIENTS_SERVICE_URL=http://localhost:5001
      - ORDERS_SERVICE_URL=http://localhost:5002
      - PURCHASES_SERVICE_URL=http://localhost:5003

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 10s
      timeout: 5s
      retries: 5

  orders-service:
    build:
      context: ./orders
    container_name: orders-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "5002:5002"

  purchases-service:
    build:
      context: ./purchases
    container_name: purchases-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "5003:5003"

  recipe-service:
    build:
      context: ./recipes
    container_name: recipe-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "5005:5005"

  ingredients-service:
    build:
      context: ./ingredients
    container_name: ingredients-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "5001:5001"
