services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 10s
      timeout: 5s
      retries: 5

  orders-service:
    build:
      context: ./orders
    container_name: orders-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "5004:5004"

  purchases-service:
    build:
      context: ./purchases
    container_name: purchases-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "5002:5002"

  recipe-service:
    build:
      context: ./recipes
    container_name: recipe-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "5000:5000"

  ingredients-service:
    build:
      context: ./ingredients
    container_name: ingredients-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "5001:5001"

  office-application:
    build:
      context: ./office
    container_name: office-application
    ports:
      - "3000:3000"
